### ISSUE TITLE
Problemas no Vagrant Up

### ISSUE THREAD

**Issue by carlosandrade** [okfn-brasil/gastos_abertos_dev#7]
Registrando aqui o problema ocorrido após executar o Vagrant Up. Talvez seja bom responder também ao e-mail que dei "UP" da Gastos Abertos em que você explicou sobre a virtual machine: 

Título do e-mail: [Gastosabertos] Ambiente de desenvolvimento com vagrant

Esta na lista gastosabertos normal mesmo (não está na dev.). 

As screenshots do problema parecem sugerir que o pepino começa na parte do Oracle. 

![screenshot 2015-12-06 10 38 21](https://cloud.githubusercontent.com/assets/355565/11615603/d995c84a-9c09-11e5-8fed-82a75e081b72.png)
![screenshot 2015-12-06 10 38 29](https://cloud.githubusercontent.com/assets/355565/11615602/d99429a4-9c09-11e5-9ddb-8da9bec237ea.png)

**Comment by aivuk** [comment]
Você está usando Mac? Você tem espaço em disco (df -h)? Nos passe o resultado de ls -l de gastos_abertos_dev-master

**Comment by aivuk** [comment]
E me diga se em algum momento deu o comando vagrant ou git clone como root ou usou sudo.

**Comment by carlosandrade** [comment]
Deu até dor no coração porque o Macbook é de 2012, mas sim tenho ainda 442 GB Livres! O hamster ainda aguenta umas boas pedaladas. 

Macbook, OS X 10.9.5

carlos@midna:~/Downloads/gastos_abertos_dev-master$ df -h
Filesystem      Size   Used  Avail Capacity  iused     ifree %iused  Mounted on
/dev/disk0s2   698Gi  285Gi  412Gi    41% 74889418 108044324   41%   /
devfs          184Ki  184Ki    0Bi   100%      638         0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0         0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0         0  100%   /home

carlos@midna:~/Downloads/gastos_abertos_dev-master$ ls -l 
total 16
-rwxr-xr-x@  1 carlos  staff     0 Oct 30 12:56 README.md
-rwxr-xr-x@  1 carlos  staff  1503 Oct 30 12:56 Vagrantfile
-rwxr-xr-x@  1 carlos  staff   293 Oct 30 12:56 autorun.sh
drwxr-xr-x@  3 carlos  staff   102 Oct 30 12:56 config
drwxr-xr-x@ 13 carlos  staff   442 Oct 30 12:56 provision

Tentei após com sudo vagrant up mas não foi também. O inicial foi sem sudo, que você está vendo o screenshot.

**Comment by aivuk** [comment]
Mas seu /home está cheio!

**Comment by aivuk** [comment]
Calma lá, não sei o que é a partição /home num Mac.

**Comment by carlosandrade** [comment]
Não creio que isso seja o problema. Instalo coisa dia e noite e nunca deu pepino com isso. Além do que pela interface de sistema esses detalhes nem aparecem. Veja a screenshot ai. 

![screenshot 2015-12-06 22 23 51](https://cloud.githubusercontent.com/assets/355565/11622250/2a60c050-9c68-11e5-96df-780b2cde905d.png)

**Comment by carlosandrade** [comment]
Depois de uma aventura ao infinito de quase 2 horas com o Edgar zanzando na minha maquina de forma remota, resolvemos instalar via virtualenv no macbook a coisa na tora. Estou só com o lado de API mas por hora basta, os outros lados são mais pesados em html e javascript e ta longe ainda do que eu sei. :-)

**Comment by aivuk** [comment]
Luiz, era algum problema com o disco virtual utilizado pelo VirtualBox. Ele possuia algum limite de tamanho e quando começava a crescer o uso dele, ele não fazia redimensionamento automático. Verifiquei que ele estava configurado pra redimensionar, mas por alguma razão não fazia. Eu sempre fico irritado quando essas ferramentas como Vagrant, Docker, que prometem facilitar a replicação de ambientes de desenvolvimento, geram mais problemas e acaba-se ao invés de gastar horas montando seu ambiente, gastando horas resolvendo problemas com elas. A Sibi teve outro problema ao tentar rodar o Vagrant, permissões nos diretórios criados pelo Vagrant e levou horas pra resolver.
